import type { Metadata } from "next"
import { Geist, Geist_Mono, Noto_Sans, Noto_Sans_SC } from "next/font/google"
import localFont from "next/font/local"

import { Layout } from "@/components/layout/layout"
import { TooltipProvider } from "@/components/ui/tooltip"
import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils"

import "./globals.css"
import "katex/dist/katex.css"

// const notoSans = Noto_Sans({ subsets: ["latin"], variable: "--font-sans" })

const notoSansSC = Noto_Sans_SC({
  subsets: ["latin"],
  variable: "--font-sans",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const firaCode = localFont({
  variable: "--font-fira-code",
  src: [
    {
      path: "./fonts/Fira_Code_v6.2/FiraCode-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Fira_Code_v6.2/FiraCode-Medium.woff2",
      weight: "500",
      style: "medium",
    },
    {
      path: "./fonts/Fira_Code_v6.2/FiraCode-Bold.woff2",
      weight: "700",
      style: "bold",
    },
  ],
  display: "swap",
})

export const metadata: Metadata = {
  title: "主页 - lorem314.io",
  // description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        // notoSans.variable,
        notoSansSC.variable,
        firaCode.variable,
      )}
    >
      <body className="flex min-h-full flex-col">
        <TooltipProvider>
          <Toaster />
          <Layout>{children}</Layout>
        </TooltipProvider>
      </body>
    </html>
  )
}
